# -*- coding: utf-8 -*-
"""clasificacion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uJghPhNhYF4A1Rz0uurWE5tkfFA7hDTb
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

# Cargar los datos
data = pd.read_csv("hombres_mujeres_data_set_bin.csv")

# Separar los datos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(data, data["clase"], test_size=0.25)

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)

model = LogisticRegression()

# Entrenar el modelo
model.fit(X_train, y_train)

# Evaluar el modelo
y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred))

import matplotlib.pyplot as plt

# Generar el diagrama de dispersión
plt.scatter(data["talla"], data["peso"])

# Mostrar el gráfico
plt.show()

# Generar el diagrama de dispersión
plt.scatter(data["talla"], data["peso"])

# Mostrar el gráfico
plt.show()

# Generar el diagrama de dispersión
plt.scatter(data["talla"], data["peso"], c=data["clase"])

# Mostrar el gráfico
plt.show()